// FLYERS
/** ACTIONS **/
export const GET_FLAYERS = "GET_FLAYERS";
export const STORED_FLAYERS = "STORED_FLAYERS";
export const ADD_FAVORITE = "ADD_FAVOURITE";
export const GET_RETAILERS = "GET_RETAILERS";
export const STORED_RETAILERS = "STORED_RETAILERS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const STORED_CATEGORIES = "STORED_CATEGORIES";
export const DO_SEARCH = 'DO_SEARCH';
export const DO_FILTER = 'DO_FILTER';
export const CLEAR_BUTTON = 'CLEAR_BUTTON';
export const FAVOURITE_TOGGLE = 'FAVOURITE_TOGGLE';

